### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by orefalo** [nghiepdev/nexus-mutation#1]
Hi, found your project my mistake.
I am new to nexus.If I may, I don't understand the benefits of your plugin.

I can define mutations with the nexus api - therefore how does your plugin help?

Thank you

**Comment by nghiepdev** [comment]
Hi @orefalo 
Following [Designing GraphQL Mutations](https://www.apollographql.com/blog/designing-graphql-mutations-e09de826ed97/)
> **The main points to consider when designing your GraphQL mutations are:**
>-  ...
> - Input object. Use a single, required, unique, input object type as an argument for easier mutation execution on the client.
> - Unique payload type. Use a unique payload type for each mutation and add the mutation’s output as a field to that payload type.
>- ...

So, If you have many mutations, you will manually define `CreateInput`, `CreatePayload`, `UpdateProductInput`, `UpdateProductPayload` and more.

The plugin will help you to define the `XXXtInput` and `XXXPayload` automatically. Your mutations are more consistent than ever.
Please check more examples in the readme.

**Comment by orefalo** [comment]
Thank you -
  I am just an old dude, pardon my ignorance - I didn't understand the examples and what they were bringing to the table

But your explanation helps,
   If I may, I think you should explicitly highlight the benefits in the README.

Sincerely
